import {readFile,writeFile,copyFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const dir='reports/layout-review-01';const cases=JSON.parse(await readFile(`${dir}/cases.json`));const measurements=JSON.parse(await readFile(`${dir}/measurements.json`));
const reviews=[
[[5,5,5,4],'良好','全5ノードが同じ中心軸に並び、4本の接続が直線。文字の欠けなし。空間−1：図自身の幅476pxに対しノード幅は約104pxで、左右の余白が大きい。'],
[[5,5,5,3],'良好','開始→在庫判断→出荷→通知→完了が同一軸。No側の待機と合流も識別でき、Yes/Noは分岐付近にある。空間−2：待機を中間段に置くためYesの直通線が長く、6ノードで高さ680pxになる。'],
[[5,3,5,4],'調整候補','承認の主経路は一直線で、修正を左に分離。経路−2：Noの下降線と再申請の戻り線が修正ノード右上で交差し、近接した折り返しを追う必要がある。空間−1：修正側の線が細い通路に密集する一方、外周に余白が残る。'],
[[5,5,5,5],'良好','fork→3状態→join→確定が上下に並び、3状態の高さと間隔も揃う。joinへの矢印は離れて到着し、並列区間が一目で分かる。fork後の共有線は並列分岐の意味と整合し減点しない。長い経路ラベルの耐性はこの例では未評価。'],
[[4,1,2,3],'要改善','API列とDB列は明確。配置−1：中央の接続量に対して列間が狭い。経路−4：中央で多数の縦線・横線・ジャンプが密集し、個別の接続先を連続して追いにくい。ラベル−3：参照・更新・記録・集計が近接し、どの線の文字か判別しにくい。空間−2：中央を圧縮したまま右・下に迂回し、小面積でも読みやすさに結び付いていない。'],
[[4,2,4,4],'調整候補','入口・アプリケーション・データ層の階層は明確。配置−1：注文APIの下がQueue、Workerの下がDBとなり、保存と購読が回り込む。経路−3：Gatewayからの転送、APIの保存、Queueからの購読が中央と外周を使い、特に購読はデータ層の下から右端を大回りする。ラベル−1：転送・配信・保存を近接する縦線と対応付ける必要がある。空間−1：枠内に余白がある一方で中央通路が狭い。'],
[[5,3,5,4],'調整候補','画面→API→内部部品の左から右への依存と、外部決済の境界が明確。経路−2：API右の縦通路を認証・監査・DB・決済への線が共有し、上部でログイン線と交差するため分岐元を追い直す必要がある。ラベルは読める。空間−1：外部決済への上方迂回で横幅820pxになり、外部側下部の空白が大きい。'],
[[5,4,5,5],'良好','顧客→注文→支払い／明細の関係が左から右へ流れ、商品も明細に直接接続する。関係名と1/Nを区別して読める。経路−1：商品→明細が途中でわずかに段差を作る。両者の接続高さを揃えれば、より単純な線にできそう。'],
[[4,5,5,4],'良好','Repositoryを上に置き、実装2クラスを同じ段に配置。実現の破線・関連の矢印・合成の菱形、多重度を識別できる。配置−1：OrderがOrderRepositoryの真下ではなく全体中央に置かれ、保存の線に横移動が入る。空間−1：CustomerRepositoryの下に大きい空白が残る。'],
[[5,3,4,4],'調整候補','長い処理名は枠内で折り返され、正常経路と書類追加の枝も分離している。経路−2：不足の枝と再審査の戻り線が左側で交差し、狭い折り返しになる。ラベル−1：戻り線のラベルが長い縦線の中央にあり、矢印から離れているため方向と対応を追い直す。空間−1：左側の長い経路ラベル用の幅と中央判断の幅が重なり、通路の余裕が少ない。']
];
const data=cases.map((c,i)=>({...c,...Object.fromEntries(['width','height','nodes','edges'].map(k=>[k,measurements[i][k]])),scores:reviews[i][0],total:reviews[i][0].reduce((a,b)=>a+b),status:reviews[i][1],reason:reviews[i][2]}));
await writeFile(`${dir}/scores.json`,JSON.stringify(data,null,2));
await copyFile('dist/finch.global.js',`${dir}/finch.snapshot.js`);
const hash=createHash('sha256').update(await readFile(`${dir}/finch.snapshot.js`)).digest('hex');
for(const c of cases){const f=`${dir}/${c.id}.html`;await writeFile(f,(await readFile(f,'utf8')).replace('../../dist/finch.global.js','./finch.snapshot.js'));}
let generator=await readFile(`${dir}/generate.mjs`,'utf8');generator=generator.replace('../../dist/finch.global.js','./finch.snapshot.js').replace("editor:true});</script>","editor:true});instance.svg.style.width=instance.geometry.width+'px';instance.svg.style.height=instance.geometry.height+'px';instance.svg.style.maxWidth='none';</script>");await writeFile(`${dir}/generate.mjs`,generator);
const intro=`# 配置・ルーティング評価 — 第1回\n\n2026-09-12。架空の10モデルを現在のローカル実装で生成し、Edgeの実ブラウザー描画をCodexが目視評価した。これは評価基準をすり合わせるための暫定採点であり、利用者による追跡時間の実験結果ではない。ライブラリ本体の修正や、採点後のレイアウト調整は行っていない。\n\n## 採点基準 v0.1\n\n4項目を各5点、計20点。同じ観察条件で比較し、各減点を表に記した。\n\n| 項目 | 観察すること |\n| --- | --- |\n| 配置 | 読む方向、主経路、階層、同段の整列、関連の近さ |\n| 経路 | 接続元・接続先を追えるか、交差の曖昧さ、共有線、迂回、折れ曲がり |\n| ラベル | 文字の欠け・重なり、線や多重度との対応、分岐条件の位置 |\n| 空間 | 可読性に必要な間隔、不要な余白、極端な縦横比、混雑の偏り |\n\n5=今回の例で支障を認めない、4=軽微な改善余地、3=追い直しが必要、2=繰り返し迷う／一部判読困難、1=主目的を大きく阻害、0=描画不能または必要情報が欠落。点差は厳密な測定単位ではない。合計とは別に、接続追跡を大きく阻害するものを「要改善」とする。\n\n交差を一律に減点しない。forkの意味に沿う共有線は許容し、接続先を誤認しやすい密集・共有を重く扱う。長さも単独では減点せず、追跡負担や空間の偏りと合わせて判断する。同じ箇所を複数項目で減点した場合は、配置・追跡・空間それぞれの影響を明記した。\n\n## 観察条件\n\n- 同じ既定テーマ・既定ルーティング。手動座標、overlay、ピン留めなし。06のみソースの意味的な階層指定としてlayout=row/columnを使用。全例が完全なヒントなし配置ではない。\n- 各図を固有寸法の100%で表示し、広い図は横スクロール。ページの外枠・最低幅600px・24pxパディングは空間採点から除外し、SVG自身の余白を見る。\n- 全10例の構文検証とブラウザー描画に成功し、ページエラー0件。PNGを10例すべて目視確認。図の自動交差数計測や全ラベルの衝突検査を行ったという意味ではない。\n- 低密度の図で高得点でも、高密度への耐性は保証しない。図種の優劣や合格率に集約せず、同一ケースの改善前後で比較する。\n- HTMLは同梱のfinch.snapshot.jsを使う。初回PNG/SVG、DSL、採点JSON、寸法・geometryを保存。ビルドSHA-256: ${hash}。作業ツリーには既存の変更があるため、コミット番号だけでは再現できない。\n\n## 結果\n\n点数の内訳は 配置 / 経路 / ラベル / 空間。\n\n| 図 | 内訳 | 合計 | 判定 | 根拠 |\n| --- | --- | --- | --- | --- |\n`;
const rows=data.map(c=>`| [${c.id} ${c.title}](${c.id}.html) · [PNG](${c.id}.png) | ${c.scores.join(' / ')} | ${c.total}/20 | ${c.status} | ${c.reason} |`).join('\n');
const conclusion=`\n\n## 基準を確認したい論点\n\n1. 05を10/20の「要改善」とする判断：交差の数よりも、接続追跡とラベルの対応を重く見ることでよいか。\n2. 03・10の交差はジャンプで識別できるが、経路を3/5とする厳しさでよいか。\n3. 02の長い正常経路は主軸維持の利点もある。空間3/5を厳しすぎると考えるか。\n4. 配置と空間の同時減点は影響が重なるため、次回は配点の統合や重み付けを検討するか。\n\n次回の候補は05の通路幅、06のデータ層の並び、03の戻り線の側をそれぞれ一つずつ変え、同じDSLの基準版と比較すること。今回の得点は固定し、基準変更時にはv0.2として10例すべてを再採点する。\n`;
await writeFile(`${dir}/review.md`,intro+rows+conclusion);
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
await writeFile(`${dir}/index.html`,`<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Finch 配置・ルーティング評価01</title><style>body{font:15px/1.7 system-ui;color:#1c3040;background:#f6f8fa;margin:0;padding:32px}main{max-width:1380px;margin:auto}h1{font-size:28px}a{color:#075fa4}table{border-collapse:collapse;background:white;width:100%}td,th{border:1px solid #d9e1e7;padding:14px;text-align:left;vertical-align:top}th{background:#eaf0f5}td:first-child{min-width:160px}td:nth-child(3){white-space:nowrap;font-weight:bold}.bad{background:#fff0ee}details{margin:18px 0;padding:18px;background:white}img{max-width:100%;height:auto}.muted{color:#536978}.num{white-space:nowrap}th:nth-child(2){min-width:140px}td:nth-child(4),th:nth-child(4){min-width:76px;white-space:nowrap}section{background:white;padding:20px;margin-top:18px}</style><main><h1>配置・ルーティング評価 — 第1回</h1><p>10例を生成し、描画結果を目視採点。<b>評価方法のすり合わせ用の暫定評価</b>です。図の名前からHTML、PNGから初回の固定画像を開けます。</p><p>配置・経路・ラベル・空間を各5点、計20点。5＝支障なし、4＝軽微、3＝追い直しが必要、2＝繰り返し迷う、1＝主目的を阻害、0＝描画不能／必要情報欠落。<br>交差数より接続の追いやすさを重視し、意味に沿ったforkの共有線は減点しません。図種間の順位付けではなく、今後の同一ケース比較の基準です。</p><p class="muted">2026-09-12 · 初期自動配置 · 手動修正なし · 全10例の構文検証成功／ブラウザーエラー0件<br>06のみ階層内のrow/column指定あり。空間評価はSVG自身を対象とし、ページ外枠の余白は除外。採点はCodexによる観察で、追跡時間の測定ではありません。</p><p><a href="review.md">詳細な評価基準と論点</a> · <a href="scores.json">採点JSON</a> · <a href="measurements.json">寸法・geometry</a></p><table><thead><tr><th>作成した図</th><th>配置 / 経路 /<br>ラベル / 空間</th><th>合計</th><th>判定</th><th>採点理由</th></tr></thead><tbody>${data.map(c=>`<tr class="${c.status==='要改善'?'bad':''}"><td><a href="${c.id}.html">${c.id}<br>${c.title}</a><br><a href="${c.id}.png">PNG</a> · <a href="${c.id}.svg">SVG</a><br><small>${c.width} × ${c.height}</small></td><td class="num">${c.scores.join(' / ')}</td><td>${c.total}/20</td><td>${c.status}</td><td>${esc(c.reason)}</td></tr>`).join('')}</tbody></table><section><b>確認したい採点判断</b><ol><li>05の接続追跡困難を重く見て10/20・要改善とする。</li><li>03・10のジャンプ付き交差を、経路3/5とする。</li><li>02の主軸維持に伴う長い直通線を、空間3/5とする。</li><li>配置と空間の影響が重なる場合の二重減点を許容するか。</li></ol><p>次回は採点方針を確定してから、同じケースの変更前後を比較します。今回の図と得点は基準版として保存します。</p></section><h2>初回描画の一覧</h2>${data.map(c=>`<details><summary>${c.id} ${c.title} — ${c.total}/20</summary><a href="${c.id}.html"><img loading="lazy" src="${c.id}.png" alt="${c.title}の初回描画"></a><p>${esc(c.reason)}</p></details>`).join('')}</main></html>`);
console.log(data.map(c=>`${c.id} ${c.total}/20`).join('\n'));
